server:
  port: 9297

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TienThuan29/jwt-gateway-eureka.git
          clone-on-start: true