server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000,http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: '*'
            allowCredentials: true
      discovery:
        locator:
          enable: true
      routes:
        - id: user-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/users/**

        - id: user-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/auth/**

        - id: ticket-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/events/**

        - id: ticket-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/tickets/**

        - id: ticket-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/tickets/generic/**

        - id: ticket-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/rating/**

        - id: ticket-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/categories/**

        - id: ticket-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/hashtags/**

        - id: admin-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/admin/**

        - id: admin-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/policy/**

        - id: admin-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/system/**

        - id: staff-service
          uri: http://localhost:9005
          predicates:
            - Path=/api/staffs/**

        - id: report-service
          uri: http://localhost:9006
          predicates:
            - Path=/api/reports/**

        - id: report-service
          uri: http://localhost:9006
          predicates:
            - Path=/api/report-type/**

        - id: email-service
          uri: http://localhost:9007
          predicates:
            - Path=/api/email/**

        - id: payments-service
          uri: http://localhost:9008
          predicates:
            - Path=/api/payments/**

        - id: payments-service
          uri: http://localhost:9008
          predicates:
            - Path=/api/transactions/**

        - id: chat-service
          uri: http://localhost:9009
          predicates:
            - Path=/**

        - id: notification-service
          uri: http://localhost:9011
          predicates:
            - Path=/api/notifications/**







