server:
  port: 9009

spring:
  application:
    name: chat-service
  data:
    mongodb:
      database: TicketResellDB
      uri: mongodb+srv://ticketresell:9999@ticketresellplatformdb.zvsc1.mongodb.net/
